name: Gone Sailing
baseurl: /gone-sailing
imagesurl: /gone-sailing/images/ 
thumbsurl: /gone-sailing/assets/thumbs/
sq500url: /gone-sailing/assets/500x500/

collections_dir: collections
collections:
  post-categories:
    output: true
    permalink: /:title/index:output_ext

defaults:
  -
    scope:
      path: ""
      type: "post-categories"
    values:
      layout: category_page


exclude: [
  "package.json",
  "package-lock.json",
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "gulpfile3x.js",
  "readme.md"
]
include: [
  "/assets/vendor/*.js"
]
sass:
    load_paths:
        - _sass
