baseurl: "/gone-sailing"
collections_dir: "_collections"
exclude: [
  "package.json",
  "package-lock.json",
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "readme.md"
]
include: [
  "/assets/vendor/*.js"
]
sass:
    load_paths:
        - _sass
