name: Gone Sailing
baseurl: 
imagesurl: https://dpyyvkdkr8dej.cloudfront.net/images
thumbsurl: https://dpyyvkdkr8dej.cloudfront.net/thumbs
sq500url:  https://dpyyvkdkr8dej.cloudfront.net/500x500
s3url: https://gone-sailing.s3.eu-west-2.amazonaws.com

collections_dir: collections
collections:
  post-categories:
    output: true
    permalink: /:title/index:output_ext

defaults:
  -
    scope:
      path: ""
      type: "post-categories"
    values:
      layout: category_page


exclude: [
  "package.json",
  "package-lock.json",
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "gulpfile3x.js",
  "readme.md"
]
include: [
  "/assets/vendor/*.js"
]
sass:
    load_paths:
        - _sass
