baseurl: /gone-sailing
imagesurl: /gone-sailing/images/ 
collections_dir: collections
collections:
  categories:
    output: true
    permalink: /:title/index:output_ext

defaults:
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: category_page


exclude: [
  "package.json",
  "package-lock.json",
  "node_modules",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile.js",
  "gulpfile3x.js",
  "readme.md"
]
include: [
  "/assets/vendor/*.js"
]
sass:
    load_paths:
        - _sass
